ALTER TYPE "SmsStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "SmsStatus" ADD VALUE IF NOT EXISTS 'READ';

ALTER TABLE "sms_logs"
ADD COLUMN IF NOT EXISTS "providerStatus" TEXT,
ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastAttemptAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "readAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "sms_logs_provider_providerId_idx"
ON "sms_logs"("provider", "providerId");
